apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: o11y
  name: collector-receiver-lb
rules:
- apiGroups: [""]
  resources:
    - endpoints
    - services
    - pods
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collector-receiver-lb
  namespace: o11y
subjects:
- kind: ServiceAccount
  name: collector-receiver-lb-collector
  namespace: o11y
roleRef:
  kind: Role
  name: collector-receiver-lb
  apiGroup: rbac.authorization.k8s.io