apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trace-loadbalance-collector
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trace-loadbalance-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trace-loadbalance-collector
subjects:
- kind: ServiceAccount
  name: trace-loadbalance-collector
  namespace: o11y