apiVersion: v2
name: otel-collectors
description: OpenTelemetry Collector stack for Kubernetes observability with Grafana Cloud
version: 1.0.0
appVersion: 0.133.0
type: application

maintainers:
- name: Platform Team
  email: platform@company.com

keywords:
- opentelemetry
- observability  
- monitoring
- grafana-cloud
- kubernetes

dependencies:
- name: kube-state-metrics
  version: "5.25.1"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: kubeStateMetrics.enabled
- name: prometheus-node-exporter
  version: "4.39.0"  
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: nodeExporter.enabled
  alias: nodeExporter

annotations:
  category: Monitoring