{{- if .Values.grafanaCloud.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafanaCloud.authSecretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "otel-collectors.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ .Values.grafanaCloud.username | b64enc | quote }}
  password: {{ .Values.grafanaCloud.password | b64enc | quote }}
{{- end }}