apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-k8s-cluster
  namespace: o11y

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-k8s-cluster
rules:
# Core API groups
- apiGroups: [""]
  resources:
    - nodes
    - nodes/stats
    - nodes/metrics
    - nodes/proxy
    - services
    - endpoints
    - pods
    - events
    - namespaces
    - persistentvolumes
    - persistentvolumeclaims
    - configmaps
    - secrets
    - serviceaccounts
    - resourcequotas
    - replicationcontrollers
  verbs: ["get", "list", "watch"]

# Apps API group  
- apiGroups: ["apps"]
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs: ["get", "list", "watch"]

# Batch API group
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list", "watch"]

# Extensions API group
- apiGroups: ["extensions"]
  resources:
    - deployments
    - daemonsets
    - replicasets
  verbs: ["get", "list", "watch"]

# Networking API group
- apiGroups: ["networking.k8s.io"]
  resources:
    - networkpolicies
    - ingresses
  verbs: ["get", "list", "watch"]

# Storage API group
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - volumeattachments
  verbs: ["get", "list", "watch"]

# Metrics API group
- apiGroups: ["metrics.k8s.io"]
  resources:
    - nodes
    - pods
  verbs: ["get", "list"]

# Custom resources
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]

# Non-resource URLs (for kubelet metrics)
- nonResourceURLs:
    - "/metrics"
    - "/metrics/cadvisor"
    - "/metrics/resource"
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-k8s-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-k8s-cluster
subjects:
- kind: ServiceAccount
  name: otel-k8s-cluster
  namespace: o11y