name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  helm-lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.15.4

    - name: Helm Lint
      run: |
        cd otelcol-scalable-chart
        helm lint .

    - name: Helm Template Test
      run: |
        cd otelcol-scalable-chart
        helm template test-release . -f test-values.yml